CREATE TABLE user_info (
  user_id INT NOT NULL AUTO_INCREMENT,
  ID VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  convert_key VARCHAR(255) NOT NULL,
  email VARCHAR(255),
  join_time TIMESTAMP NOT NULL,
  is_admin BOOLEAN NOT NULL,
  PRIMARY KEY (user_id)
);